---
- name: Check if Nix is installed
  ansible.builtin.stat:
    path: /nix/var/nix/profiles/default/bin/nix
  register: nix_installed

- name: Download Nix installer
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix-install.sh
    mode: "0755"
  when: not nix_installed.stat.exists

- name: Install Nix (daemon mode)
  ansible.builtin.command:
    cmd: /tmp/nix-install.sh --daemon --no-modify-profile --yes
  become: true
  when: not nix_installed.stat.exists

- name: Ensure /etc/nix exists
  ansible.builtin.file:
    path: /etc/nix
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Enable Nix flakes
  ansible.builtin.lineinfile:
    path: /etc/nix/nix.conf
    regexp: '^experimental-features\s*='
    line: 'experimental-features = nix-command flakes'
    create: true
    owner: root
    group: root
    mode: "0644"
  become: true


# Stow the home manager files now
# Run the nix run command to setup home manager now
#- name: Symlink the home-manager configs
#  ansible.builtin.file:
#    dest: file.123.txt
#    state: exists
